[build-system]
requires = ["uv_build>=0.11.1,<0.12.0"]
build-backend = "uv_build"

[project]
name = "eerepr"
version = "0.1.2"
description = "Code Editor-style reprs for Earth Engine data in a Jupyter notebook."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
authors = [{ name = "Aaron Zuspan" }]
keywords = [
    "earthengine",
    "gee",
    "html",
    "jupyter",
    "notebook",
    "reprs",
]
dependencies = [
    "earthengine-api",
]

[project.urls]
Homepage = "https://github.com/aazuspan/eerepr"

[dependency-groups]
dev = [
    "poethepoet",
    "ruff>=0.15.8",
    "pytest",
    "pytest-cov",
    "pytest-regressions",
    "pytest-mock",
    "mypy>=1.14.1",
]

[tool.ruff.lint]
select = ["E", "I", "F", "B", "FA", "UP", "ISC", "PT", "Q", "RET", "SIM", "PERF"]
exclude = ["*.ipynb"]

[tool.mypy]
ignore_missing_imports = true
exclude = ["tests/*"]

[tool.poe.tasks]
lint = "ruff check . --fix"
format = "ruff format ."
type-check = "mypy ."
check = ["lint", "format", "type-check"]
test = "pytest"
coverage = "pytest . --cov=eerepr {args}"
preview = "uv run python -m tests.preview_html"
