# Adapted from: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish to PyPI
on:
    push:
        tags:
            # Publish when a tag is pushed
            - '*'

jobs:
    build:
        name: Build distribution
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
              with:
                persist-credentials: false

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: '3.x'

            - name: Build distribution
              run: uv build --clear --no-sources

            - name: Store packages
              uses: actions/upload-artifact@v7
              with:
                name: python-package-distributions
                path: dist/
                    
    publish-to-pypi:
        name: Publish to PyPI
        runs-on: ubuntu-latest
        needs:
        - build
        environment:
            name: pypi
            url: https://pypi.org/p/eerepr
        permissions:
            id-token: write  # IMPORTANT: mandatory for trusted publishing

        steps:
        - name: Download dists
          uses: actions/download-artifact@v8
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish distribution to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1

