# This workflow sets up the Earth Engine token and runs all tests.

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .[test]
    - name: Store EE token
      run: |
        python ./.github/scripts/make_ee_token.py
      env:
        EE_TOKEN: ${{ secrets.EE_TOKEN }}
    - name: Test with pytest
      run: |
        pytest .